# log
logging:
    level:
        root: INFO
        edu.uneti.stem: DEBUG
        org.springframework: INFO
    path: logs
    max-history: 3
    max-file-size: 100MB

# database
spring:
    r2dbc:
        url: r2dbc:postgresql://localhost:5432/stem_db_dev
        username: postgres
        password: postgres